# -*- coding: utf-8 -*-
"""projet_TAI/FD_scene2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17Lun9GNk4_NMBq0ZHYDXHb9_fJrDmMip

## Scène 2
Extraire avec précision la zone lumineuse (disque) à l’intérieur de cette image.
"""

import cv2
import numpy as np
from skimage import exposure

# Load images
img = cv2.imread('/content/Scene_2.png')
gt = cv2.imread('/content/GT2.png', 0)  # ground truth (binary)

# --- 1. Canal vert ---
green = img[:, :, 1]

# --- 2. CLAHE ---
clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(10,10))
enhanced = clahe.apply(green)

# --- 3. Filtre médian ---
blur = cv2.medianBlur(enhanced, 5)

# --- 4. Top-hat (isoler zones très brillantes) ---
kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE, (35,35))
tophat = cv2.morphologyEx(blur, cv2.MORPH_TOPHAT, kernel)

# --- 5. Seuillage Otsu ---
_, thresh = cv2.threshold(tophat, 0, 255, cv2.THRESH_BINARY + cv2.THRESH_OTSU)

# --- 6. Morphologie ---
kernel_small = np.ones((8,8), np.uint8)
clean = cv2.morphologyEx(thresh, cv2.MORPH_OPEN, kernel_small)
clean = cv2.morphologyEx(clean, cv2.MORPH_CLOSE, kernel_small)

# --- 7. Filtrage des composantes ---
num_labels, labels, stats, centroids = cv2.connectedComponentsWithStats(clean)

mask = np.zeros_like(clean)

best_score = 0
best_label = 0

for i in range(1, num_labels):
    area = stats[i, cv2.CC_STAT_AREA]

    if area < 500 :  # enlever bruit
        continue

    # Bounding box
    x, y, w, h, _ = stats[i]

    # Circularité approx (rapport largeur/hauteur)
    ratio = w / h if h != 0 else 0

    # Score simple : aire + circularité
    score = area * (1 - abs(1 - ratio))

    if score > best_score:
        best_score = score
        best_label = i

mask[labels == best_label] = 255

import matplotlib.pyplot as plt

plt.figure(figsize=(12,4))

plt.subplot(1,4,1)
plt.title("Canal vert")
plt.imshow(green, cmap='gray')

plt.subplot(1,4,2)
plt.title("CLAHE + Median")
plt.imshow(blur, cmap='gray')

plt.subplot(1,4,3)
plt.title("Segmentation")
plt.imshow(mask, cmap='gray')

plt.subplot(1,4,4)
plt.title("GT")
plt.imshow(gt, cmap='gray')

plt.show()

import numpy as np
import cv2 # Import cv2 for image resizing

def compute_metrics(pred, gt):
    # Binarisation (0 ou 1)
    pred = (pred > 0).astype(np.uint8)
    gt = (gt > 0).astype(np.uint8)

    # Calcul TP, FP, FN
    TP = np.sum((pred == 1) & (gt == 1))
    FP = np.sum((pred == 1) & (gt == 0))
    FN = np.sum((pred == 0) & (gt == 1))

    # Métriques
    IoU = TP / (TP + FP + FN + 1e-8)
    Dice = (2 * TP) / (2 * TP + FP + FN + 1e-8)
    Precision = TP / (TP + FP + 1e-8)
    Recall = TP / (TP + FN + 1e-8)

    return IoU, Dice, Precision, Recall

# Resize gt to match mask's shape before computing metrics
# cv2.resize expects (width, height) for dsize, so mask.shape[::-1] or (mask.shape[1], mask.shape[0])
if gt.shape != mask.shape:
    gt_resized = cv2.resize(gt, (mask.shape[1], mask.shape[0]), interpolation=cv2.INTER_NEAREST)
else:
    gt_resized = gt

iou, dice, precision, recall = compute_metrics(mask, gt_resized)

print(f"IoU       : {iou:.4f}")
print(f"Dice      : {dice:.4f}")
print(f"Precision : {precision:.4f}")
print(f"Recall    : {recall:.4f}")